/**
 * Seed script — loads services, homams, testimonials, and page defaults into PostgreSQL.
 * Run with: node server/migrations/002_seed.mjs
 */
import { createRequire } from "module";
import { fileURLToPath } from "url";
import path from "path";
import pg from "pg";

const { Pool } = pg;

// Load the compiled TS outputs or use dynamic import workaround
// We'll directly define seed data inline to avoid TS compilation dependency

if (!process.env.PG_HOST || !process.env.PG_PASSWORD) {
  throw new Error("Set PG_HOST, PG_DATABASE, PG_USER, PG_PASSWORD in .env.local before running migrations. Run: export $(grep -v '^#' .env.local | xargs)");
}
const pool = new Pool({
  host: process.env.PG_HOST,
  port: Number(process.env.PG_PORT) || 5432,
  database: process.env.PG_DATABASE,
  user: process.env.PG_USER,
  password: process.env.PG_PASSWORD,
  ssl: process.env.PG_SSL === "false" ? false : { rejectUnauthorized: false },
});

async function query(text, params) {
  return pool.query(text, params);
}

// ── Services ────────────────────────────────────────────────
const commonReceive = [
  "Personal phone / WhatsApp consultation with Guruji",
  "Analysis of your birth chart (kundli) for this concern",
  "Clear, honest guidance in simple language",
  "Practical remedies, mantras and spiritual measures",
  "Suggested homam or pooja if required",
  "Follow-up instructions for lasting results",
];

const bookingFaq = {
  question: "How do I book this consultation?",
  answer: "Fill the enquiry form on this page with your birth details and question, or tap WhatsApp / Call. Guruji reviews your details and confirms a consultation slot. Payment can be made via Razorpay, UPI, or by uploading a payment screenshot.",
};

const confidentialFaq = {
  question: "Is my information kept confidential?",
  answer: "Yes. Your birth details and everything you share stay strictly private and are used only to prepare your guidance.",
};

const services = [
  { slug:"love-relationship-problems", title:"Love & Relationship Problems", icon:"💖", gradient:"from-rose-500/30 to-fuchsia-600/30", short_description:"Understand love compatibility, resolve misunderstandings, and bring harmony to your relationship.", full_description:"Relationships flourish when planetary energies between two people are in balance. Through careful analysis of Venus and the 7th house, Guruji reveals the root cause of misunderstandings, emotional distance, or repeated conflict — and guides you with Vedic remedies to restore love, trust, and understanding.", problem:"Frequent arguments, emotional distance, one-sided love, doubts about compatibility, or a relationship that keeps hitting the same wall can leave you anxious and confused. Vedic astrology looks beyond the surface to the planetary influences shaping your bond.", price:501, duration:"20–30 min consultation", gradient2:"from-rose-500/30 to-fuchsia-600/30", analysis:["Venus (love & attraction) and 7th house (partnership) analysis","Relationship compatibility and guna matching","Timing of harmony and difficult transit periods","Doshas affecting love and intimacy","Remedies to strengthen understanding and trust"], receive:commonReceive, benefits:["Clarity on compatibility and long-term potential","Solutions for recurring misunderstandings","Remedies to attract and stabilize love"], remedies:["Venus-strengthening mantras and gemstone guidance","Specific pooja / homam if indicated","Simple daily spiritual practices for harmony"], faqs:[{question:"Can you tell if my relationship will work out?",answer:"Astrology gives indicative guidance on compatibility and favourable periods. Guruji offers honest insights and remedies, but your choices and effort matter most."},bookingFaq,confidentialFaq], featured:true, display_order:1 },
  { slug:"marriage-delay-divorce-issues", title:"Marriage Delay & Divorce Issues", icon:"💍", gradient:"from-amber-500/30 to-rose-600/30", short_description:"Guidance for late marriage, Manglik dosha, and restoring marital harmony.", full_description:"Delays in marriage or strain within one often trace back to Manglik dosha, afflicted 7th house lords, or difficult Saturn/Rahu influences. Guruji examines your chart to identify obstacles and recommends time-tested remedies to open the path to marriage and peace within it.", problem:"Marriage proposals falling through, unexplained delays, family pressure, or a marriage under constant strain can be deeply stressful. Understanding the planetary cause brings both relief and a way forward.", price:751, duration:"25–35 min consultation", analysis:["Manglik (Mangal) dosha detection and severity","7th house, Venus and Jupiter marriage indicators","Late-marriage yogas and favourable marriage periods","Compatibility and dosha cancellation checks","Remedies for marital harmony"], receive:commonReceive, benefits:["Know the real reason behind marriage delay","Manglik dosha clarity and remedies","Guidance to restore harmony in an existing marriage"], remedies:["Mangal Dosha remedies and recommended homam","Auspicious timing (muhurta) guidance","Mantras and vrat for a smooth married life"], faqs:[{question:"I am Manglik — is that a serious problem?",answer:"Manglik dosha varies in strength and is often cancelled by other placements. Guruji assesses the actual severity and suggests remedies — it is rarely a reason for fear."},bookingFaq,confidentialFaq], featured:true, display_order:2 },
  { slug:"career-confusion-job-problems", title:"Career Confusion & Job Problems", icon:"💼", gradient:"from-sky-500/30 to-indigo-600/30", short_description:"Find your ideal career direction and overcome job instability or fear of loss.", full_description:"Your 10th house, along with the Sun and Saturn, holds the blueprint of your professional life. Guruji analyses these to reveal your natural strengths, favourable career fields, and the periods when growth, change, or caution is advised.", problem:"Feeling stuck, repeated job changes, fear of losing your position, or confusion about which path to choose can drain your confidence. Vedic astrology points to the direction where you will truly thrive.", price:751, duration:"25–35 min consultation", analysis:["10th house (career), Sun (authority) and Saturn (discipline) analysis","Best-suited career fields and skills","Dasha and transit timing for job change or promotion","Obstacles causing instability or delays","Remedies to strengthen career growth"], receive:commonReceive, benefits:["Clarity on the right career direction","Timing for job change, promotion or business","Remedies to remove career blockages"], remedies:["Saturn and Sun strengthening remedies","Career-focused homam if indicated","Mantras and disciplines for steady growth"], faqs:[{question:"Can astrology tell me which field is best for me?",answer:"Your chart highlights natural aptitudes and favourable fields. Guruji combines this with practical guidance so you can make confident, grounded decisions."},bookingFaq,confidentialFaq], featured:true, display_order:3 },
  { slug:"financial-instability-debt-problems", title:"Financial Instability & Debt Problems", icon:"💰", gradient:"from-emerald-500/30 to-amber-600/30", short_description:"Break wealth blockages, find debt relief, and stabilize your finances.", full_description:"Wealth flows through Jupiter, Venus and Mercury, supported by the 2nd and 11th houses. When these are afflicted, money slips away or debt accumulates. Guruji identifies the blockage and prescribes remedies to invite stability and abundance.", problem:"Money that never seems to stay, mounting debt, blocked income, or repeated financial setbacks create constant worry. Understanding the planetary pattern is the first step to changing it.", price:999, duration:"30 min consultation", analysis:["Jupiter, Venus and Mercury (wealth) analysis","2nd house (savings) and 11th house (gains) review","Causes of wealth blockage and financial leakage","Debt-relief timing and favourable periods","Remedies to attract and retain wealth"], receive:commonReceive, benefits:["Identify what is blocking your money flow","Practical guidance for debt relief","Remedies to attract steady abundance"], remedies:["Lakshmi Kubera pooja / homam guidance","Wealth mantras and charitable measures","Gemstone and daily practice suggestions"], faqs:[{question:"Will astrology help me clear my debt?",answer:"Astrology reveals favourable periods and remedies to ease financial pressure, but it works best alongside disciplined planning. Guruji guides you on both."},bookingFaq,confidentialFaq], featured:false, display_order:4 },
  { slug:"family-conflicts-domestic-issues", title:"Family Conflicts & Domestic Issues", icon:"🏡", gradient:"from-teal-500/30 to-purple-600/30", short_description:"Restore peace at home and heal parental or domestic conflict.", full_description:"The 4th house and the Moon govern home, mother, and emotional peace. When disturbed, family harmony suffers. Guruji examines these influences to uncover the source of tension and recommends remedies to bring warmth and understanding back home.", problem:"Constant friction at home, disputes between family members, or a heavy, restless atmosphere affects everyone. Vedic astrology helps identify and soothe the underlying planetary causes.", price:501, duration:"20–30 min consultation", analysis:["4th house (home & peace) and Moon (emotions) analysis","Planetary causes of family tension","Parental and generational conflict indicators","Favourable periods for reconciliation","Remedies for domestic harmony"], receive:commonReceive, benefits:["Understand the root of ongoing conflict","Guidance to restore peace and warmth","Remedies for a harmonious home"], remedies:["Moon-strengthening remedies and mantras","Peace-giving pooja / homam if indicated","Simple household spiritual practices"], faqs:[{question:"Can remedies really improve family relationships?",answer:"Remedies calm afflicted energies and support a more peaceful atmosphere. Combined with patience and understanding, many families notice a real shift."},bookingFaq,confidentialFaq], featured:false, display_order:5 },
  { slug:"mental-stress-anxiety-depression", title:"Mental Stress, Anxiety & Depression", icon:"🧘", gradient:"from-indigo-500/30 to-cyan-600/30", short_description:"Find emotional peace through Moon–Saturn analysis and spiritual remedies.", full_description:"The Moon governs the mind and Saturn governs fear and heaviness. A difficult Moon–Saturn relationship can create persistent worry, low mood, or restlessness. Guruji offers gentle spiritual guidance and remedies to bring calm and inner balance.", problem:"Ongoing anxiety, overthinking, low energy, or a heavy mind can feel isolating. Vedic astrology and spiritual remedies offer a supportive path toward peace — alongside, never instead of, professional care where needed.", price:501, duration:"25 min consultation", analysis:["Moon (mind) and Saturn (fear/heaviness) analysis","Chandra dosha and mental-peace indicators","Challenging transit and dasha periods","Spiritual causes of restlessness","Peace-giving remedies and practices"], receive:commonReceive, benefits:["Understand planetary influences on your mind","Calming mantras and spiritual practices","A supportive, compassionate consultation"], remedies:["Moon-strengthening and peace mantras","Maha Mrityunjaya / Chandra homam guidance","Meditation and daily grounding practices"], faqs:[{question:"Is this a substitute for medical treatment?",answer:"No. Astrological guidance is spiritual and supportive. For medical concerns including anxiety or depression, please also consult qualified health professionals."},bookingFaq,confidentialFaq], featured:false, display_order:6 },
  { slug:"health-wellness-astrology", title:"Health & Wellness Astrology", icon:"🌿", gradient:"from-lime-500/30 to-emerald-600/30", short_description:"Astrological indications for health, vitality, and wellbeing with supportive remedies.", full_description:"The 6th house, Ascendant, and planets like Sun, Moon and Saturn offer indications about vitality and health tendencies. Guruji highlights areas to care for and recommends spiritual remedies to support your wellbeing.", problem:"Recurring health concerns, low vitality, or a wish to strengthen wellbeing lead many to seek astrological indications. This guidance complements — and never replaces — proper medical care.", price:751, duration:"25–30 min consultation", analysis:["Ascendant, 6th house and health-significator planets","Vitality and constitution indicators","Challenging periods to stay cautious","Doshas linked to wellbeing","Supportive spiritual remedies"], receive:commonReceive, benefits:["Awareness of health tendencies in your chart","Supportive remedies for vitality","Guidance on favourable periods for care"], remedies:["Dhanvantari / Maha Mrityunjaya homam guidance","Health-supporting mantras and practices","Charity and lifestyle suggestions"], faqs:[{question:"Can astrology diagnose my illness?",answer:"Astrology gives indicative tendencies, not medical diagnosis. Always consult a doctor for diagnosis and treatment; Guruji's guidance is spiritual support."},bookingFaq,confidentialFaq], featured:false, display_order:7 },
  { slug:"education-exam-success", title:"Education & Exam Success", icon:"📚", gradient:"from-yellow-500/30 to-orange-600/30", short_description:"Improve focus, overcome learning obstacles, and succeed in studies and exams.", full_description:"Mercury, Jupiter and the 4th/5th houses shape learning, memory and academic success, with Saraswati's blessings for knowledge. Guruji analyses these to help students overcome concentration issues and study obstacles.", problem:"Difficulty concentrating, exam anxiety, or a bright student who cannot show results — these often have planetary influences that can be gently strengthened with the right guidance.", price:501, duration:"20–25 min consultation", analysis:["Mercury (intellect) and Jupiter (wisdom) analysis","4th & 5th house education indicators","Concentration and memory obstacles","Favourable periods for exams and admissions","Saraswati-related remedies"], receive:commonReceive, benefits:["Guidance to improve focus and memory","Support for exam confidence","Remedies for academic success"], remedies:["Saraswati homam and mantra guidance","Study-supporting spiritual practices","Favourable timing for important exams"], faqs:[{question:"Which remedies help students the most?",answer:"Saraswati mantras, a strengthened Mercury/Jupiter, and disciplined routines help most. Guruji tailors remedies to the student's chart."},bookingFaq,confidentialFaq], featured:false, display_order:8 },
  { slug:"business-growth-partnership-problems", title:"Business Growth & Partnership Problems", icon:"📈", gradient:"from-orange-500/30 to-red-600/30", short_description:"Grow your business, resolve partnership issues, and time key decisions well.", full_description:"Business success is shaped by the 7th house (partnerships), 10th house (profession), and wealth planets. Guruji analyses these to guide expansion, resolve partner disputes, and choose auspicious timing for important moves.", problem:"Stalled growth, unreliable partners, or uncertainty about expanding can put your livelihood at risk. Vedic timing and remedies help you act with confidence.", price:1100, duration:"30–40 min consultation", analysis:["7th house (partnership) and 10th house (business) analysis","Wealth and growth yogas","Partnership compatibility and dispute causes","Auspicious timing for launches and deals","Remedies to accelerate growth"], receive:commonReceive, benefits:["Clarity on partnership decisions","Timing for expansion and key deals","Remedies to remove business obstacles"], remedies:["Lakshmi Kubera / Ganapathi homam guidance","Business-strengthening mantras","Auspicious muhurta for important steps"], faqs:[{question:"Can you help me choose a good business partner?",answer:"Guruji can assess partnership compatibility and favourable timing from both charts where available, helping you decide with greater clarity."},bookingFaq,confidentialFaq], featured:false, display_order:9 },
  { slug:"property-legal-court-case-guidance", title:"Property, Legal & Court Case Guidance", icon:"⚖️", gradient:"from-slate-500/30 to-purple-700/30", short_description:"Guidance for property delays, legal stress, and court matters.", full_description:"Property and legal matters are governed by the 4th house (property), Mars, and Saturn (delays, disputes, discipline). Guruji analyses these to indicate favourable periods and remedies for property purchases, disputes, and court cases.", problem:"Blocked property deals, prolonged legal battles, or the stress of a court case can weigh heavily. Vedic astrology highlights favourable timing and remedies to ease the path.", price:1100, duration:"30–40 min consultation", analysis:["4th house (property) analysis","Mars and Saturn (disputes, delays) review","Favourable periods for property and legal matters","Doshas contributing to obstacles","Remedies for resolution and relief"], receive:commonReceive, benefits:["Guidance on property purchase or sale timing","Support and remedies for legal stress","Clarity on favourable and cautious periods"], remedies:["Sudarshana / Navagraha homam guidance","Mars & Saturn pacifying remedies","Mantras and charity for legal relief"], faqs:[{question:"Can astrology tell me if I will win my case?",answer:"Astrology indicates favourable and difficult periods and offers remedies, but outcomes also depend on facts and legal process. Guruji offers honest, supportive guidance."},bookingFaq,confidentialFaq], featured:false, display_order:10 },
  { slug:"jataka-matching-kundali-compatibility", title:"Jataka Matching & Kundali Compatibility", icon:"💑", gradient:"from-rose-400/30 to-amber-500/30", short_description:"Detailed kundali matching for marriage compatibility — doshas, guna milan, and auspicious timing.", full_description:"Jataka matching goes beyond a simple guna score. Guruji analyses both charts for Manglik dosha, Nadi dosha, matching of Moon signs, Venus, and key houses to give an honest, detailed compatibility reading before marriage.", problem:"Families and couples want to be sure their charts are compatible before committing to marriage. A superficial matching can miss important doshas or wrongly reject a compatible pair. Guruji provides clarity.", price:1100, duration:"30–40 min consultation", analysis:["Guna milan (Ashtakuta) score and details","Manglik dosha check for both charts","Nadi, Bhakoot and Gana dosha evaluation","7th house and Venus compatibility","Auspicious periods for marriage (muhurta guidance)"], receive:commonReceive, benefits:["Honest compatibility verdict with reasoning","Identification and remedy for doshas","Guidance on auspicious marriage timing"], remedies:["Dosha-cancellation remedies if required","Recommended homam before the wedding","Auspicious muhurta suggestions"], faqs:[{question:"Do both partners need to be present?",answer:"No. Guruji needs the birth details (date, time, place) of both individuals. The consultation can be with one partner."},bookingFaq,confidentialFaq], featured:true, display_order:11 },
  { slug:"marriage-date-prediction", title:"Marriage Date Prediction", icon:"📅", gradient:"from-pink-500/30 to-amber-400/30", short_description:"Know your likely marriage period, auspicious date and day from your birth chart.", full_description:"Using dasha, antardasha and transit analysis, Guruji identifies the most likely period, year, and even auspicious dates/days for your marriage — along with practical guidance on timing your search or proposal.", problem:"Wondering when you will get married or whether this is the right year can be stressful. A careful chart reading reveals the timing windows and what to do to support them.", price:2000, duration:"20–30 min consultation", analysis:["7th house lord dasha and antardasha timing","Venus and Jupiter transit periods","Favourable years and months for marriage","Auspicious marriage date and day identification","Obstacles to be addressed in the near term"], receive:["Predicted marriage period (year/month range)","Auspicious date and day recommendations","Practical guidance on next steps","Remedies to support timely marriage","Follow-up instructions"], benefits:["Know when to expect or plan your marriage","Auspicious date and day guidance","Remedies to remove delays"], remedies:["Mangal / Venus strengthening remedies","Specific vrat or mantra for marriage blessing","Homam guidance if transit is challenging"], faqs:[{question:"Can astrology give me an exact date?",answer:"Astrology gives the most favourable windows (year, month range) and auspicious dates within them. Exact certainty is not possible, but the guidance is highly indicative."},bookingFaq,confidentialFaq], featured:false, display_order:12 },
  { slug:"janna-jataka-comprehensive-birth-chart", title:"Janna Jataka — Full Birth Chart Analysis", icon:"🌟", gradient:"from-amber-400/30 to-orange-500/30", short_description:"Complete life reading from your birth chart — all life areas, problems and remedies in one session.", full_description:"Janna Jataka is a comprehensive reading of your entire birth chart. Guruji examines all 12 houses, major dashas, and key yogas to give you a complete picture of your life — strengths, challenges, timing for major events, and remedies for each area.", problem:"Many people want a holistic view of their chart rather than focusing on just one problem. This full reading covers career, relationships, health, finances, and life purpose in one thorough session.", price:3000, duration:"45–60 min consultation", analysis:["All 12 houses — career, love, health, wealth, family","Lagna (Ascendant) and life-purpose indicators","Major dasha periods and what they mean for you","Key yogas — auspicious and challenging","Doshas present and their relative strength","Remedies for each identified challenge area"], receive:["Full verbal analysis of all major life areas","Written summary of key findings sent by email","Personalised remedies for each challenge","Timing guidance for important decisions","30-day WhatsApp follow-up for questions"], benefits:["Complete life clarity from a single session","Understand your strengths and life purpose","Personalised remedies for all challenge areas"], remedies:["Multi-planet strengthening remedies as needed","Tailored mantra and charity guidance","Recommended homam sequence if indicated"], faqs:[{question:"How is this different from a regular consultation?",answer:"A regular consultation focuses on one area. Janna Jataka covers your entire chart holistically — all life areas, all dashas, all doshas — in a single in-depth session."},bookingFaq,confidentialFaq], featured:true, display_order:13 },
  { slug:"family-children-prediction", title:"Family & Children Prediction", icon:"👨‍👩‍👧‍👦", gradient:"from-teal-400/30 to-emerald-600/30", short_description:"Guidance on children, family harmony and parenting using both spouses' birth charts.", full_description:"For married couples, Guruji analyses both charts to address questions about children — timing, number, gender indications, and any obstacles. Family harmony, parenting challenges, and blessings for the household are also covered.", problem:"Delays in having children, concerns about the family's wellbeing, or questions about parenthood timing often have astrological explanations. Using both spouses' charts provides the most complete picture.", price:1500, duration:"30–40 min consultation", analysis:["5th house (children) analysis for both spouses","Jupiter (children, blessings) placement and strength","Timing of children — dasha and transit windows","Obstacles to conception or family harmony","Remedies to support family blessings"], receive:["Children timing guidance (likely windows)","Family harmony remedies","Mantras and pooja for blessings","Practical follow-up guidance","WhatsApp support after the session"], benefits:["Clarity on children timing and prospects","Remedies for delays or complications","Family harmony and parenting guidance"], remedies:["Santana Gopala homam guidance","Jupiter-strengthening remedies","Vrat and mantra for children blessings"], faqs:[{question:"Do both husband and wife need to share birth details?",answer:"For the most accurate reading, both partners' birth details are needed. Guruji can work with one chart if the other is unavailable, but the two-chart reading is more comprehensive."},bookingFaq,confidentialFaq], featured:false, display_order:14 },
  { slug:"gemstone-recommendation", title:"Gemstone Recommendation", icon:"💎", gradient:"from-cyan-400/30 to-blue-600/30", short_description:"Personalised gemstone guidance based on your birth chart to strengthen favourable planets.", full_description:"Vedic gemstones (ratnas) are worn to strengthen benefic planets in your chart. Guruji examines your chart to recommend the right stone, metal, weight, and finger — and equally important, which stones to avoid.", problem:"Wearing the wrong gemstone can aggravate malefic planets and cause harm. Many people wear stones based on sun sign alone, which is inaccurate. A proper chart-based recommendation is essential.", price:501, duration:"20 min consultation", analysis:["Lagna lord and benefic planet identification","Stones to strengthen and stones to avoid","Correct weight (ratti), metal and setting","Which finger and which hand","Activation (energisation) guidance"], receive:["Written gemstone recommendation by email","Stones to wear and stones to strictly avoid","Wearing procedure and activation mantra","Where to source quality certified gems (guidance)","Follow-up support via WhatsApp"], benefits:["Strengthen the right planets for your chart","Avoid harmful stones that weaken your chart","Simple, practical guidance with full details"], remedies:["Primary gemstone recommendation with full details","Substitute (upratna) option if primary is costly","Activation mantra and day of wearing"], faqs:[{question:"Which gemstone is best for me?",answer:"It depends entirely on your birth chart. There is no one-size-fits-all answer. Guruji recommends only chart-appropriate stones — and advises which to avoid."},bookingFaq,confidentialFaq], featured:false, display_order:15 },
  { slug:"rahu-kuja-dosha-analysis", title:"Rahu & Kuja (Mars) Dosha Analysis", icon:"🔥", gradient:"from-red-600/30 to-violet-700/30", short_description:"Detailed assessment of Rahu dosha and Kuja (Manglik) dosha — severity, effects and remedies.", full_description:"Rahu and Kuja (Mars) are among the most talked-about planets when it comes to doshas. Guruji conducts a thorough analysis of both to determine their actual strength in your chart, the areas they affect, and the specific remedies to pacify them.", problem:"Fear about Rahu dosha or Manglik dosha is common, but their severity varies greatly from chart to chart. Many doshas are partially or fully cancelled by other placements. Guruji gives you the honest picture.", price:1100, duration:"30 min consultation", analysis:["Rahu position, strength and dosha assessment","Kuja (Manglik) dosha presence and severity","Cancellation factors (dosha parihara) check","Houses and life areas affected","Targeted remedies for each dosha"], receive:commonReceive, benefits:["Honest assessment — severity, not scare","Clarity on cancellation of doshas","Specific remedies for each dosha present"], remedies:["Rahu shanti puja / Kuja Graha shanti","Rahu-Ketu or Mangal dosha homam guidance","Mantras, vrat and charity for pacification"], faqs:[{question:"Is Manglik dosha really that serious?",answer:"In most charts, Manglik dosha is partially cancelled and its effects are moderate. Guruji assesses the actual severity honestly — it is rarely a reason for alarm."},bookingFaq,confidentialFaq], featured:false, display_order:16 },
  { slug:"black-magic-removal", title:"Black Magic & Negative Energy Removal", icon:"🛡️", gradient:"from-gray-800/30 to-purple-900/30", short_description:"Identification and removal of black magic, evil eye, and negative energies through Vedic rituals.", full_description:"Some situations — repeated unexplained failures, sudden health deterioration, family discord, or nightmares — may indicate black magic or strong evil eye. Guruji assesses this through chart analysis and specific diagnostic techniques, then performs the appropriate Vedic ritual for removal and protection.", problem:"Persistent, unexplained negative patterns in life — despite remedies and effort — sometimes point to external negative influence. This service addresses such situations with discretion and powerful Vedic counter-measures.", price:5000, duration:"Call-based assessment first", analysis:["Chart analysis for external negative influences","Evil eye (drishti) and black magic indicators","Affected life areas and intensity","Appropriate Vedic ritual identification","Protection measures after removal"], receive:["Initial assessment call with Guruji","Appropriate ritual or homam for removal","Protection mantras and measures","Follow-up check after the ritual","Ongoing protection guidance"], benefits:["Removal of identified negative influences","Spiritual protection going forward","Peace of mind and restoration of energy"], remedies:["Sudarshana / Durga homam for protection","Specific removal ritual as assessed","Kavach (protective mantra) and daily practice"], faqs:[{question:"How do I know if I have black magic on me?",answer:"Guruji assesses this through chart analysis and a detailed discussion. There is no charge for the initial assessment call."},bookingFaq,confidentialFaq], featured:false, display_order:17 },
  { slug:"pitra-dosha-rahu-dasha-relief", title:"Pitra Dosha & Rahu Dasha Relief", icon:"🪔", gradient:"from-amber-700/30 to-purple-800/30", short_description:"Quick dosha report and remedies for Pitra Dosha and Rahu Dasha — delivered by email.", full_description:"A focused, fast analysis of Pitra Dosha (ancestral dosha) and Rahu Dasha effects on your life. Guruji assesses the presence and severity based on your birth details and sends a concise written report with targeted remedies by email.", problem:"Pitra dosha and Rahu dasha are behind many unexplained family problems, career obstacles, and recurring misfortune. A quick identification lets you act on the remedy immediately.", price:2000, duration:"Email report within 5–10 min", analysis:["Pitra dosha presence and strength","Rahu dasha / antardasha current period","Life areas most affected","Quick dosha reason summary","Targeted remedy guidance"], receive:["Written email report within 5–10 minutes","Dosha reason explained clearly","Specific remedies for Pitra dosha","Rahu dasha pacification guidance","WhatsApp support for follow-up questions"], benefits:["Fast clarity — no waiting days for a report","Actionable remedies you can start immediately","Affordable and focused"], remedies:["Pitra tarpana / Narayana Bali guidance","Rahu shanti mantra and donation guidance","Simple immediate measures to reduce effects"], faqs:[{question:"How quickly will I receive the report?",answer:"Guruji aims to send the email report within 5–10 minutes of receiving your birth details. During busy periods it may take up to 30 minutes."},bookingFaq,confidentialFaq], featured:false, display_order:18 },
];

const homams = [
  { slug:"ganapathi-homam", name:"Ganapathi Homam", icon:"🕉️", gradient:"from-amber-500/30 to-orange-600/30", short_benefit:"Removes obstacles and blesses new beginnings.", full_description:"Ganapathi Homam invokes Lord Ganesha, the remover of obstacles, before any important venture. It clears hurdles, invites auspicious beginnings, and is the traditional first step before other rituals.", price:2000, duration:"1.5 – 2 hours", benefits:["Removes obstacles from important ventures","Blesses new beginnings and fresh starts","Invites success, wisdom and prosperity"], suitable_for:["Starting a business, job or new project","Before weddings, housewarming or other rituals","Anyone facing repeated obstacles"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi (or birth details) and preferred date via the booking form or WhatsApp. Guruji confirms an auspicious muhurta, performs the homam with proper Vedic procedure, and sends prasadam details and photos/updates. Payment via Razorpay, UPI, or screenshot upload.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes. Guruji performs the homam in your name (sankalpa) with your birth details. You do not need to be physically present, though you are welcome to attend where possible."},{question:"How do I book and pay for a homam?",answer:"Submit the booking form or message on WhatsApp. Once an auspicious date is confirmed, pay via Razorpay, UPI, or upload a payment screenshot. You will receive confirmation and updates."},{question:"Will the homam guarantee results?",answer:"Homams are sacred spiritual practices performed with devotion. They offer spiritual support and blessings; results are not guaranteed and should be approached with faith rather than expectation."}], featured:true, display_order:1 },
  { slug:"navagraha-homam", name:"Navagraha Homam", icon:"🪐", gradient:"from-indigo-500/30 to-purple-700/30", short_benefit:"Balances all 9 planets and their doshas.", full_description:"Navagraha Homam propitiates all nine planets to harmonize their influence in your life. It reduces the effects of malefic planetary periods and doshas, restoring balance and smoothing life's difficulties.", price:3500, duration:"2 – 3 hours", benefits:["Balances the influence of all nine planets","Reduces malefic dasha and transit effects","Brings overall stability and relief"], suitable_for:["Those going through difficult planetary periods","Multiple doshas or persistent obstacles","General planetary peace and protection"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi (or birth details) and preferred date via the booking form or WhatsApp.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or message on WhatsApp."},{question:"Will the homam guarantee results?",answer:"Homams offer spiritual support and blessings; results should be approached with faith."}], featured:true, display_order:2 },
  { slug:"lakshmi-kubera-homam", name:"Lakshmi Kubera Homam", icon:"💰", gradient:"from-yellow-500/30 to-emerald-600/30", short_benefit:"Wealth, abundance and debt relief.", full_description:"Lakshmi Kubera Homam invokes Goddess Lakshmi and Lord Kubera, the treasurer of the gods, to attract wealth, remove financial blockages, and support debt relief and lasting prosperity.", price:3000, duration:"2 – 3 hours", benefits:["Attracts wealth and abundance","Supports debt relief and financial stability","Removes blockages to prosperity"], suitable_for:["Financial instability or mounting debt","Business owners seeking growth","Anyone seeking sustained prosperity"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi (or birth details) and preferred date via the booking form or WhatsApp.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Homams offer spiritual support; approach with faith."}], featured:true, display_order:3 },
  { slug:"surya-homam", name:"Surya Homam", icon:"☀️", gradient:"from-orange-500/30 to-red-600/30", short_benefit:"Authority, confidence and father-related blessings.", full_description:"Surya Homam honours the Sun God to strengthen a weak Sun, boosting confidence, authority, leadership, and vitality.", price:2000, duration:"1.5 – 2 hours", benefits:["Strengthens confidence and leadership","Improves authority and public standing","Blesses father-related matters and vitality"], suitable_for:["Weak or afflicted Sun in the chart","Career authority and recognition","Health and vitality support"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date via the booking form or WhatsApp.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:true, display_order:4 },
  { slug:"chandra-homam", name:"Chandra Homam", icon:"🌙", gradient:"from-sky-400/30 to-indigo-600/30", short_benefit:"Mind peace, emotional balance and mother-related blessings.", full_description:"Chandra Homam propitiates the Moon to calm the mind, balance emotions, and ease anxiety and restlessness.", price:2000, duration:"1.5 – 2 hours", benefits:["Calms the mind and balances emotions","Eases anxiety and restlessness","Blesses mother-related matters"], suitable_for:["Weak or afflicted Moon","Anxiety, overthinking, emotional turbulence","Seeking mental peace"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:true, display_order:5 },
  { slug:"rudra-homam", name:"Rudra Homam", icon:"🔱", gradient:"from-slate-400/30 to-purple-700/30", short_benefit:"Removes negativity, evil eye and grants inner peace.", full_description:"Rudra Homam invokes Lord Shiva in his Rudra form to destroy negativity, dispel the evil eye and negative energies.", price:3000, duration:"2 – 3 hours", benefits:["Removes negativity and evil-eye effects","Grants protection and courage","Bestows deep inner peace"], suitable_for:["Persistent negativity or obstacles","Feeling of being affected by evil eye","Seeking spiritual protection and peace"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:true, display_order:6 },
  { slug:"maha-mrityunjaya-homam", name:"Maha Mrityunjaya Homam", icon:"🛡️", gradient:"from-emerald-500/30 to-teal-700/30", short_benefit:"Longevity, healing and protection from illness.", full_description:"Maha Mrityunjaya Homam chants the powerful Mrityunjaya mantra to invoke Lord Shiva's healing grace — supporting longevity, recovery from illness, and protection from untimely dangers.", price:3500, duration:"2 – 3 hours", benefits:["Supports healing and recovery","Blesses longevity and vitality","Protects from illness and dangers"], suitable_for:["Health challenges or recovery periods","Protection during difficult transits","Wellbeing of family members"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:7 },
  { slug:"saraswati-homam", name:"Saraswati Homam", icon:"📖", gradient:"from-yellow-400/30 to-sky-500/30", short_benefit:"Knowledge, education, focus and exam success.", full_description:"Saraswati Homam invokes Goddess Saraswati to bless students and seekers with focus, memory, clarity, and success in education and exams.", price:2000, duration:"1.5 – 2 hours", benefits:["Improves focus, memory and clarity","Blesses education and exam success","Enhances wisdom and creativity"], suitable_for:["Students and those preparing for exams","Concentration and learning difficulties","Artists, teachers and knowledge-seekers"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:8 },
  { slug:"durga-homam", name:"Durga Homam", icon:"🗡️", gradient:"from-red-500/30 to-fuchsia-700/30", short_benefit:"Protection, courage and removal of negative energy.", full_description:"Durga Homam invokes Goddess Durga to grant protection from enemies and negative forces, courage in adversity.", price:3000, duration:"2 – 3 hours", benefits:["Protection from enemies and negativity","Courage and strength in adversity","Removal of fear and obstacles"], suitable_for:["Facing enemies, threats or hostility","Need for protection and courage","Removal of persistent negative energy"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:9 },
  { slug:"sudarshana-homam", name:"Sudarshana Homam", icon:"🌀", gradient:"from-cyan-500/30 to-blue-700/30", short_benefit:"Protection from enemies and obstacles.", full_description:"Sudarshana Homam invokes Lord Vishnu's Sudarshana Chakra to destroy negative influences and provide powerful protection.", price:3500, duration:"2 – 3 hours", benefits:["Powerful protection from enemies","Destroys negative influences and obstacles","Shields from hidden dangers"], suitable_for:["Strong protection needs","Persistent enemies or legal troubles","Removal of black magic / negativity"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:10 },
  { slug:"dhanvantari-homam", name:"Dhanvantari Homam", icon:"🌿", gradient:"from-green-500/30 to-emerald-700/30", short_benefit:"Health and healing blessings.", full_description:"Dhanvantari Homam invokes Lord Dhanvantari, the divine physician, to bless health, support recovery from illness.", price:2500, duration:"2 – 3 hours", benefits:["Blesses health and healing","Supports recovery from illness","Promotes vitality and wellbeing"], suitable_for:["Chronic or recurring health issues","Recovery and convalescence","General health and vitality"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:11 },
  { slug:"ayushya-homam", name:"Ayushya Homam", icon:"🪔", gradient:"from-amber-400/30 to-yellow-600/30", short_benefit:"Long life and wellness.", full_description:"Ayushya Homam is performed for longevity, health, and protection — traditionally done for children and family members.", price:2000, duration:"2 hours", benefits:["Blesses long life and wellness","Protects health and vitality","Traditionally auspicious for children"], suitable_for:["Birthdays and milestone blessings","Children and family members","Longevity and health protection"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:12 },
  { slug:"shani-shanti-homam", name:"Shani Shanti Homam", icon:"🪨", gradient:"from-slate-500/30 to-indigo-700/30", short_benefit:"Relief from Saturn's difficulties; discipline and stability.", full_description:"Shani Shanti Homam propitiates Lord Shani (Saturn) to ease the hardships of Sade Sati, Dhaiya, and Saturn's difficult periods.", price:2500, duration:"2 hours", benefits:["Eases Sade Sati and Saturn difficulties","Reduces delays, struggles and hardship","Brings discipline and stability"], suitable_for:["Those in Sade Sati or Shani dasha","Repeated delays and obstacles","Seeking patience and stability"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:13 },
  { slug:"rahu-ketu-shanti-homam", name:"Rahu Ketu Shanti Homam", icon:"☄️", gradient:"from-violet-500/30 to-slate-700/30", short_benefit:"Dosha relief and spiritual balance.", full_description:"Rahu Ketu Shanti Homam pacifies the shadow planets Rahu and Ketu to relieve their doshas.", price:3000, duration:"2 – 3 hours", benefits:["Relieves Rahu-Ketu doshas","Reduces confusion and sudden obstacles","Restores spiritual and mental balance"], suitable_for:["Kaal Sarp dosha or Rahu-Ketu afflictions","Sudden ups and downs in life","Seeking clarity and balance"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:14 },
  { slug:"mangal-dosha-homam", name:"Mangal Dosha Homam", icon:"🔴", gradient:"from-red-500/30 to-rose-700/30", short_benefit:"Relief from marriage obstacles and Manglik dosha.", full_description:"Mangal Dosha Homam propitiates Mars (Mangal) to reduce the effects of Manglik dosha.", price:2500, duration:"2 hours", benefits:["Reduces Manglik (Mangal) dosha effects","Eases marriage delays and obstacles","Supports marital harmony"], suitable_for:["Manglik individuals seeking relief","Marriage delays and repeated obstacles","Harmony in married life"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:15 },
  { slug:"kadali-vivaha", name:"Kadali Vivaha", icon:"🌴", gradient:"from-emerald-500/30 to-amber-600/30", short_benefit:"Sacred Vedic ritual to nullify Manglik dosha and marriage obstacles.", full_description:"Kadali Vivaha is a sacred Vedic ritual performed primarily for men affected by Manglik Dosha or severe planetary obstacles in marriage.", price:3000, duration:"2 – 3 hours", benefits:["Removes severe Manglik dosha effects for marriage","Clears planetary hurdles causing marital delays","Paves the way for a peaceful and prosperous married life"], suitable_for:["Men facing severe Manglik dosha","Repeated marriage delays or broken engagements","Astrological remedies before formal wedding"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:16 },
  { slug:"kumbha-vivaha", name:"Kumbha Vivaha", icon:"🏺", gradient:"from-amber-500/30 to-rose-600/30", short_benefit:"Spiritual ritual to overcome Manglik & Vidhava dosha for marriage harmony.", full_description:"Kumbha Vivaha is an authentic Vedic ritual performed for individuals (especially women) having strong Manglik Dosha, double Manglik, or Vidhava Dosha.", price:3000, duration:"2 – 3 hours", benefits:["Neutralizes strong Manglik and Vidhava doshas","Protects longevity and harmony in future marriage","Eliminates fear of astrological incompatibilities"], suitable_for:["Women or individuals with strong Manglik / 7th house doshas","Delay or anxiety regarding marriage compatibility","Spiritual protection before entering wedlock"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:17 },
  { slug:"moksha-narayana-bali-tila-homa", name:"Moksha Narayana Bali (Tila Homa)", icon:"🪔", gradient:"from-purple-600/30 to-slate-700/30", short_benefit:"Pitr dosha relief, ancestral peace, and liberation from ancestral curses.", full_description:"Moksha Narayana Bali (Tila Homa) is a powerful Vedic ritual performed for the peace and liberation (moksha) of departed ancestors.", price:5000, duration:"3 – 4 hours", benefits:["Removes Pitru Dosha and ancestral curses","Grants peace (moksha) to departed ancestors","Clears unexplained family, health, and career blockages"], suitable_for:["Presence of Pitru Dosha in birth chart","Unexplained ancestral issues or family hurdles","Seeking ancestral blessings for lineage and growth"], pooja_items:["Sacred firewood (samidha) and ghee","Homa dravyas and herbs","Flowers, fruits and prasadam","Deity-specific offerings"], booking_instructions:"Share your name, nakshatra/rashi and preferred date.", faqs:[{question:"Can the homam be performed on my behalf?",answer:"Yes."},{question:"How do I book?",answer:"Submit the booking form or WhatsApp."},{question:"Will the homam guarantee results?",answer:"Approach with faith."}], featured:false, display_order:18 },
];

const testimonials_seed = [
  { name:"Priya Sharma", location:"Bangalore", rating:5, service_type:"consultation", text:"Guruji's reading was incredibly accurate. He identified the root cause of my marriage delay and the remedies he suggested brought results within 3 months. Truly blessed to have found him.", date:"2025-08-01", avatar_initial:"P", featured:true, display_order:1 },
  { name:"Rajesh Kumar", location:"Hyderabad", rating:5, service_type:"homam", text:"We booked the Ganapathi Homam before starting our new business. The energy felt completely different afterwards. Our launch went smoothly and the business has been growing steadily.", date:"2025-07-15", avatar_initial:"R", featured:true, display_order:2 },
  { name:"Ananya Krishnan", location:"Chennai", rating:5, service_type:"birth-chart", text:"The birth chart PDF was so detailed — I was amazed at how accurately it described my personality and the challenges I've been facing. The remedies are practical and I've started following them.", date:"2025-07-10", avatar_initial:"A", featured:true, display_order:3 },
  { name:"Suresh Patel", location:"Ahmedabad", rating:5, service_type:"consultation", text:"I had been struggling with career instability for years. After Guruji's consultation and the Saturn remedies, I finally got a stable government job. Highly recommend for anyone facing career problems.", date:"2025-06-20", avatar_initial:"S", featured:true, display_order:4 },
  { name:"Meena Nair", location:"Kochi", rating:5, service_type:"consultation", text:"Guruji's guidance on family conflicts was spot on. The peace mantras and simple remedies he suggested have genuinely helped — our home feels more harmonious now.", date:"2025-06-05", avatar_initial:"M", featured:false, display_order:5 },
  { name:"Vikram Singh", location:"Delhi", rating:5, service_type:"homam", text:"The Navagraha Homam was performed with full devotion. Guruji sent videos and photos throughout. We could feel the positive shift almost immediately. Will book again for sure.", date:"2025-05-18", avatar_initial:"V", featured:false, display_order:6 },
];

const page_defaults = [
  { slug:"birth-chart-pdf", title:"Birth Chart PDF", content:{ eyebrow:"Vedic Kundli Report", title:"Birth Chart PDF", subtitle:"Get a detailed Vedic kundli report prepared with your birth details.", price:2000, priceNote:"Delivered within 48 hours to your email", includes:["Full birth chart (Rashi and Navamsa)","Planet positions, strengths and aspects","Lagna and planetary degree analysis","Major dasha and antardasha timelines","Yogas — auspicious and challenging","Dosha identification and severity","Remedy recommendations for each dosha","Career, relationship and financial indications"], faqs:[{question:"What birth details do I need to provide?",answer:"Date of birth (DD/MM/YYYY), time of birth (as accurate as possible), and place of birth (city, state, country)."},{question:"How is this different from free online birth charts?",answer:"Online tools generate charts automatically. Guruji reviews every chart personally and adds his interpretation, doshas analysis, yogas, and tailored remedies — something no automated tool can provide."},{question:"Can I get the report if I don't know my exact birth time?",answer:"A birth chart without accurate birth time is less precise for house and ascendant predictions. Guruji will note this and provide what is possible, focusing on planetary positions and dashas."}] } },
  { slug:"chat-with-guruji", title:"Chat with Guruji", content:{ eyebrow:"Live Guidance", title:"Chat with Guruji", subtitle:"Get live Vedic guidance directly from Guruji.", price:null, priceNote:"", includes:[], faqs:[{question:"How does chat with Guruji work?",answer:"Send your question via WhatsApp or the chat interface. Guruji responds with Vedic guidance, usually within a few hours during working hours (8am–9pm IST)."},{question:"Is the first message free?",answer:"Yes, you can send an initial question for free. Deeper consultation and birth chart analysis are priced separately."}] } },
  { slug:"palm-reading", title:"Instant Palm Reader", content:{ eyebrow:"Instant Analysis", title:"Instant Palm Reader", subtitle:"Upload a photo of your palm and receive an instant Vedic palmistry reading — then go deeper with Guruji.", price:null, priceNote:"", includes:[], faqs:[] } },
];

async function seed() {
  console.log("Seeding services...");
  for (const s of services) {
    await query(
      `INSERT INTO services (slug, title, category_slug, icon, short_description, full_description, problem, price, duration, gradient, analysis, receive, benefits, remedies, faqs, featured, display_order, active)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,true)
       ON CONFLICT (slug) DO UPDATE SET
         title=EXCLUDED.title, icon=EXCLUDED.icon, short_description=EXCLUDED.short_description,
         full_description=EXCLUDED.full_description, problem=EXCLUDED.problem, price=EXCLUDED.price,
         duration=EXCLUDED.duration, gradient=EXCLUDED.gradient, analysis=EXCLUDED.analysis,
         receive=EXCLUDED.receive, benefits=EXCLUDED.benefits, remedies=EXCLUDED.remedies,
         faqs=EXCLUDED.faqs, featured=EXCLUDED.featured, display_order=EXCLUDED.display_order,
         updated_at=now()`,
      [s.slug, s.title, s.categorySlug||'astrology-consultations', s.icon, s.short_description, s.full_description,
       s.problem, s.price, s.duration, s.gradient,
       JSON.stringify(s.analysis), JSON.stringify(s.receive), JSON.stringify(s.benefits),
       JSON.stringify(s.remedies), JSON.stringify(s.faqs), s.featured, s.display_order]
    );
  }
  console.log(`Seeded ${services.length} services`);

  console.log("Seeding homams...");
  for (const h of homams) {
    await query(
      `INSERT INTO homams (slug, name, icon, short_benefit, full_description, price, duration, gradient, benefits, suitable_for, pooja_items, booking_instructions, faqs, featured, display_order, active)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,true)
       ON CONFLICT (slug) DO UPDATE SET
         name=EXCLUDED.name, icon=EXCLUDED.icon, short_benefit=EXCLUDED.short_benefit,
         full_description=EXCLUDED.full_description, price=EXCLUDED.price, duration=EXCLUDED.duration,
         gradient=EXCLUDED.gradient, benefits=EXCLUDED.benefits, suitable_for=EXCLUDED.suitable_for,
         pooja_items=EXCLUDED.pooja_items, booking_instructions=EXCLUDED.booking_instructions,
         faqs=EXCLUDED.faqs, featured=EXCLUDED.featured, display_order=EXCLUDED.display_order,
         updated_at=now()`,
      [h.slug, h.name, h.icon, h.short_benefit, h.full_description, h.price, h.duration, h.gradient,
       JSON.stringify(h.benefits), JSON.stringify(h.suitable_for), JSON.stringify(h.pooja_items),
       h.booking_instructions, JSON.stringify(h.faqs), h.featured, h.display_order]
    );
  }
  console.log(`Seeded ${homams.length} homams`);

  console.log("Seeding testimonials...");
  for (const t of testimonials_seed) {
    await query(
      `INSERT INTO testimonials (name, location, rating, service_type, text, date, avatar_initial, featured, display_order, active)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,true)
       ON CONFLICT DO NOTHING`,
      [t.name, t.location, t.rating, t.service_type, t.text, t.date, t.avatar_initial, t.featured, t.display_order]
    );
  }
  console.log(`Seeded ${testimonials_seed.length} testimonials`);

  console.log("Seeding pages...");
  for (const p of page_defaults) {
    await query(
      `INSERT INTO pages (slug, title, content, active) VALUES ($1,$2,$3,true)
       ON CONFLICT (slug) DO UPDATE SET title=EXCLUDED.title, content=EXCLUDED.content, updated_at=now()`,
      [p.slug, p.title, JSON.stringify(p.content)]
    );
  }
  console.log(`Seeded ${page_defaults.length} pages`);
}

seed().then(() => {
  console.log("Seed complete.");
  pool.end();
}).catch(e => {
  console.error("Seed error:", e.message);
  pool.end();
  process.exit(1);
});
